//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialiteWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligacao_Tag
    {
        public int Ligacao_TagID { get; set; }
        public int LigacaoID { get; set; }
        public int TagID { get; set; }
    }
}
