//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialiteWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ligacaos
    {
        public int LigacaoID { get; set; }
        public int User1ID { get; set; }
        public int User2ID { get; set; }
        public int Forca { get; set; }
        public string DataDeInicio { get; set; }
        public Nullable<int> EstadoDaLigacaoID { get; set; }
    }
}
