//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialiteWebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceStatus", Namespace="http://schemas.datacontract.org/2004/07/SocialiteWebService")]
    [System.SerializableAttribute()]
    public partial class ServiceStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OnlineUsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUsers {
            get {
                return this.TotalUsersField;
            }
            set {
                if ((this.TotalUsersField.Equals(value) != true)) {
                    this.TotalUsersField = value;
                    this.RaisePropertyChanged("TotalUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int OnlineUsers {
            get {
                return this.OnlineUsersField;
            }
            set {
                if ((this.OnlineUsersField.Equals(value) != true)) {
                    this.OnlineUsersField = value;
                    this.RaisePropertyChanged("OnlineUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/SocialiteWebService")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserMoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UsertagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] UserFriendsIDsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string UserMood {
            get {
                return this.UserMoodField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMoodField, value) != true)) {
                    this.UserMoodField = value;
                    this.RaisePropertyChanged("UserMood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] Usertags {
            get {
                return this.UsertagsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsertagsField, value) != true)) {
                    this.UsertagsField = value;
                    this.RaisePropertyChanged("Usertags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int[] UserFriendsIDs {
            get {
                return this.UserFriendsIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFriendsIDsField, value) != true)) {
                    this.UserFriendsIDsField = value;
                    this.RaisePropertyChanged("UserFriendsIDs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SocialiteOperations")]
    public interface SocialiteOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Login", ReplyAction="http://tempuri.org/SocialiteOperations/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Login", ReplyAction="http://tempuri.org/SocialiteOperations/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Logout", ReplyAction="http://tempuri.org/SocialiteOperations/LogoutResponse")]
        string Logout(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Logout", ReplyAction="http://tempuri.org/SocialiteOperations/LogoutResponse")]
        System.Threading.Tasks.Task<string> LogoutAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Status", ReplyAction="http://tempuri.org/SocialiteOperations/StatusResponse")]
        SocialiteWebService.ServiceReference1.ServiceStatus Status();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/Status", ReplyAction="http://tempuri.org/SocialiteOperations/StatusResponse")]
        System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.ServiceStatus> StatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetUserData", ReplyAction="http://tempuri.org/SocialiteOperations/GetUserDataResponse")]
        SocialiteWebService.ServiceReference1.UserData GetUserData(int userid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetUserData", ReplyAction="http://tempuri.org/SocialiteOperations/GetUserDataResponse")]
        System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.UserData> GetUserDataAsync(int userid, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetCurrentUserData", ReplyAction="http://tempuri.org/SocialiteOperations/GetCurrentUserDataResponse")]
        SocialiteWebService.ServiceReference1.UserData GetCurrentUserData(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetCurrentUserData", ReplyAction="http://tempuri.org/SocialiteOperations/GetCurrentUserDataResponse")]
        System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.UserData> GetCurrentUserDataAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetWord", ReplyAction="http://tempuri.org/SocialiteOperations/GetWordResponse")]
        string GetWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetWord", ReplyAction="http://tempuri.org/SocialiteOperations/GetWordResponse")]
        System.Threading.Tasks.Task<string> GetWordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetCategory", ReplyAction="http://tempuri.org/SocialiteOperations/GetCategoryResponse")]
        string GetCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/GetCategory", ReplyAction="http://tempuri.org/SocialiteOperations/GetCategoryResponse")]
        System.Threading.Tasks.Task<string> GetCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/CompareWord", ReplyAction="http://tempuri.org/SocialiteOperations/CompareWordResponse")]
        string CompareWord(string palavra, string tentativa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SocialiteOperations/CompareWord", ReplyAction="http://tempuri.org/SocialiteOperations/CompareWordResponse")]
        System.Threading.Tasks.Task<string> CompareWordAsync(string palavra, string tentativa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SocialiteOperationsChannel : SocialiteWebService.ServiceReference1.SocialiteOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialiteOperationsClient : System.ServiceModel.ClientBase<SocialiteWebService.ServiceReference1.SocialiteOperations>, SocialiteWebService.ServiceReference1.SocialiteOperations {
        
        public SocialiteOperationsClient() {
        }
        
        public SocialiteOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialiteOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialiteOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialiteOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string Logout(string token) {
            return base.Channel.Logout(token);
        }
        
        public System.Threading.Tasks.Task<string> LogoutAsync(string token) {
            return base.Channel.LogoutAsync(token);
        }
        
        public SocialiteWebService.ServiceReference1.ServiceStatus Status() {
            return base.Channel.Status();
        }
        
        public System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.ServiceStatus> StatusAsync() {
            return base.Channel.StatusAsync();
        }
        
        public SocialiteWebService.ServiceReference1.UserData GetUserData(int userid, string token) {
            return base.Channel.GetUserData(userid, token);
        }
        
        public System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.UserData> GetUserDataAsync(int userid, string token) {
            return base.Channel.GetUserDataAsync(userid, token);
        }
        
        public SocialiteWebService.ServiceReference1.UserData GetCurrentUserData(string token) {
            return base.Channel.GetCurrentUserData(token);
        }
        
        public System.Threading.Tasks.Task<SocialiteWebService.ServiceReference1.UserData> GetCurrentUserDataAsync(string token) {
            return base.Channel.GetCurrentUserDataAsync(token);
        }
        
        public string GetWord() {
            return base.Channel.GetWord();
        }
        
        public System.Threading.Tasks.Task<string> GetWordAsync() {
            return base.Channel.GetWordAsync();
        }
        
        public string GetCategory() {
            return base.Channel.GetCategory();
        }
        
        public System.Threading.Tasks.Task<string> GetCategoryAsync() {
            return base.Channel.GetCategoryAsync();
        }
        
        public string CompareWord(string palavra, string tentativa) {
            return base.Channel.CompareWord(palavra, tentativa);
        }
        
        public System.Threading.Tasks.Task<string> CompareWordAsync(string palavra, string tentativa) {
            return base.Channel.CompareWordAsync(palavra, tentativa);
        }
    }
}
