
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IService_Login_InputMessage;
        WS_MESSAGE_DESCRIPTION IService_Login_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IService
        {
            struct  // BasicHttpBinding_IService_Login
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IService_Login;
            } BasicHttpBinding_IService_Login;
            WS_OPERATION_DESCRIPTION* operations[1];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IService;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IService
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IService;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IService_Login_InputMessageactionName;  // http://tempuri.org/IService/Login
            WS_XML_STRING IService_Login_OutputMessageactionName;  // http://tempuri.org/IService/LoginResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IService_LoginParamStruct 
{
    WCHAR** nick;
    WCHAR** password;
    WCHAR** LoginResult;
} BasicHttpBinding_IService_LoginParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IService_LoginOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IService_LoginCallback _operation = (BasicHttpBinding_IService_LoginCallback)_callback;
    BasicHttpBinding_IService_LoginParamStruct *_stack =(BasicHttpBinding_IService_LoginParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->nick),
        *(_stack->password),
        (_stack->LoginResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IService_Login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService_Login_InputMessageactionName, // http://tempuri.org/IService/Login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Login, 
        },    // message description for IService_Login_InputMessage
        {  // message description for IService_Login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService_Login_OutputMessageactionName, // http://tempuri.org/IService/LoginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.LoginResponse, 
        },    // message description for IService_Login_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IService,
            {  // BasicHttpBinding_IService_Login
                {  // parameter descriptions for BasicHttpBinding_IService_Login
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IService_Login
                {  // operation description for BasicHttpBinding_IService_Login
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService_Login_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService_Login_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService.BasicHttpBinding_IService_Login.params,
                    BasicHttpBinding_IService_LoginOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IService_Login
            },  // BasicHttpBinding_IService_Login
            {  // array of operations for BasicHttpBinding_IService
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService.BasicHttpBinding_IService_Login.BasicHttpBinding_IService_Login,
            },  // array of operations for BasicHttpBinding_IService
            {  // contract description for BasicHttpBinding_IService
            1,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService.operations,
            },  // end of contract description for BasicHttpBinding_IService
        },  // BasicHttpBinding_IService
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IService,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService/Login",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService/LoginResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // 0f003163-2b68-48e2-97d7-a9b52bcac696 
        { 0x0f003163, 0x2b68, 0x48e2, { 0x97, 0xd7, 0xa9,0xb5, 0x2b, 0xca, 0xc6, 0x96 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        2,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IService_Login
HRESULT WINAPI BasicHttpBinding_IService_Login(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* nick, 
    _In_opt_z_ WCHAR* password, 
    _Outptr_opt_result_z_ WCHAR** LoginResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &nick;
    _argList[1] = &password;
    _argList[2] = &LoginResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService.BasicHttpBinding_IService_Login.BasicHttpBinding_IService_Login,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IService_Login_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService_Login_InputMessageactionName, // http://tempuri.org/IService/Login
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Login, 
        },    // message description for IService_Login_InputMessage
        {  // message description for IService_Login_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService_Login_OutputMessageactionName, // http://tempuri.org/IService/LoginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.LoginResponse, 
        },    // message description for IService_Login_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IService
            1,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService.operations,
        },  // end of BasicHttpBinding_IService
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IService
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IService_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IService),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IService_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IServiceFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IService;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IService),
        serviceEndpoint,
        error);
}
